package com.unitbv.myquiz.api.settings;

public class ControllerSettings {

    public static final int PAGE_SIZE = 10;
    public static final String DEFAULT_PAGE = "1";
    public static final String DEFAULT_PAGE_SIZE = "10";
    public static final String ATTR_PAGE_SIZE = "pageSize";
    public static final String ATTR_PAGE_NUMBER= "page";
    public static final String ATTR_TOTAL_PAGES = "totalPages";
    public static final String ATTR_TOTAL_ELEMENTS = "totalElements";

    public static final String ATTR_AUTHOR = "author";
    public static final String HEADER_AUTHORIZATION = "Authorization" ;
    public static final String BEARER_PREFIX = "Bearer ";
    public static final String ATTR_AUTHOR_LIST = "authorList";

    public static final String ATTR_LOGGED_IN_USER = "loggedInUser";
    public static final String ATTR_JWT_TOKEN = "jwtToken";
    public static final String ATTR_LOGIN_ERROR = "loginError";
    public static final String ATTR_USERNAME = "username";
    public static final String ATTR_REGISTER_ERROR = "registerError";
    public static final String ATTR_REGISTER_ERROR_MSG = "registerErrorMsg";
    public static final String REDIRECT_HOME = "redirect:/question-banks";
    public static final String VIEW_LOGIN = "login";
    public static final String VIEW_REGISTER = "register";
    public static final String DEFAULT_REGISTRATION_ERROR = "Registration failed. Try again.";
    public static final String DEFAULT_INTERNAL_ERROR = "Internal server error. Try again.";
    public static final String KEY_SUCCESS = "success";
    public static final String KEY_TOKEN = "token";
    // Course
    public static final String ATTR_COURSES = "courses";
    public static final String ATTR_COURSE = "course";
    public static final String ATTR_COURSE_ID = "courseId";
    public static final String ATTR_MESSAGE = "message";
    public static final String VIEW_COURSE_LIST = "course-list";
    public static final String VIEW_COURSE_EDIT = "course-edit";
    public static final String VIEW_COURSE_DETAILS = "course-details";
    public static final String VIEW_DEFAULT_COURSES_FORM = "default-courses-form";
    public static final String VIEW_DATA_MANAGEMENT = "admin/data-management";
    public static final String VIEW_REDIRECT_COURSES = "redirect:/courses";
    public static final String VIEW_REDIRECT_ADMIN_DATA = "redirect:/admin/data";
    public static final String API_COURSES = "/courses/";
    public static final String API_COURSES_RECOMPUTE_DUPLICATES_SUFFIX = "/recompute-duplicates";
    public static final String API_COURSES_EXPORT_XML_SUFFIX = "/export-xml";
    public static final String API_COURSES_CREATE_DEFAULTS_SUFFIX = "create-defaults";
    public static final String API_COURSES_RECOMPUTE_HISTORY_SUFFIX = "/recompute-history";
    public static final String API_COURSES_RECOMPUTE_WITH_STRATEGY_SUFFIX = "/recompute-with-strategy";
    public static final String API_COURSES_DUPLICATE_STATISTICS_SUFFIX = "/duplicate-statistics";
    public static final String API_COURSES_CLEAR_DUPLICATES_SUFFIX = "/clear-duplicates";
    public static final String API_DATA_EXPORT_SQL = "/data/export-sql";
    public static final String API_DATA_IMPORT_SQL = "/data/import-sql";
    public static final String API_DATA_DELETE_ALL = "/data/deleteall";
    public static final String FILE_COURSE_XML_PREFIX = "course_";
    public static final String FILE_COURSE_XML_SUFFIX = "_all_questionBanks.xml";
    public static final String FILE_MYQUIZ_BACKUP_SQL = "myquiz_backup.sql";
    public static final String HEADER_ATTACHMENT_FILENAME_PREFIX = "attachment; filename=";
    public static final String CONTENT_TYPE_SQL_UTF8 = "application/sql; charset=UTF-8";
    public static final String PATH_AUTH_LOGIN = "/auth/login";
    public static final String PATH_DUPLICATE_MANAGEMENT = "/duplicate-management";
    public static final String PATH_ADMIN_USERS = "/admin/users";
    public static final String REDIRECT_ADMIN_USERS = "redirect:/admin/users";
    public static final String REDIRECT_ACCESS_DENIED = "redirect:/?error=Access+denied";
    public static final String PERMISSION_MODIFY_USER = "MODIFY_USER";
    public static final String VIEW_ADMIN_USER_LIST = "admin/user-list";
    public static final String VIEW_ADMIN_USER_EDIT = "admin/user-edit";
    public static final String API_ADMIN_USERS = "/users";
    public static final String API_ADMIN_ROLES = "/roles";
    public static final String API_ADMIN_ENABLED_SUFFIX = "/enabled";
    public static final String ATTR_USERS = "users";
    public static final String ATTR_USER = "user";
    public static final String ATTR_ALL_ROLES = "allRoles";
    public static final String ATTR_USER_ROLES = "userRoles";
    public static final String MSG_FAILED_LOAD_USERS = "Failed to load users";
    public static final String MSG_FAILED_LOAD_USER = "Failed to load user";
    public static final String MSG_FAILED_UPDATE_USER = "Failed to update user";
    public static final String MSG_FAILED_ASSIGN_ROLE = "Failed to assign role";
    public static final String MSG_FAILED_REMOVE_ROLE = "Failed to remove role";
    public static final String MSG_FAILED_DELETE_USER = "Failed to delete user";
    public static final String MSG_COURSE_CREATED_SUCCESS = "Course created successfully";
    public static final String MSG_COURSE_UPDATED_SUCCESS = "Course updated successfully";
    public static final String MSG_COURSE_DELETED_SUCCESS = "Course deleted successfully";
    public static final String MSG_RECOMPUTE_COMPLETED = "Recompute completed.";
    public static final String MSG_RECOMPUTE_STARTED_PREFIX = "Recompute started: ";
    public static final String MSG_COURSE_NOT_FOUND_RECOMPUTE = "Course not found for duplicate recompute.";
    public static final String MSG_COULD_NOT_RECOMPUTE_DUPLICATES = "Could not recompute duplicates. Please try again later.";
    public static final String MSG_COURSE_NOT_FOUND_EXPORT = "Course not found";
    public static final String MSG_ACCESS_DENIED = "Access denied";
    public static final String MSG_EXPORT_FAILED = "Export failed";
    public static final String MSG_DEFAULT_COURSES_CREATED_PREFIX = "Successfully created ";
    public static final String MSG_DEFAULT_COURSES_CREATED_SUFFIX = " default courses";
    public static final String MSG_COULD_NOT_CREATE_DEFAULT_COURSES = "Could not create default courses. Please try again later.";
    public static final String MSG_SQL_FILE_REQUIRED = "Please select a SQL file to import.";
    public static final String MSG_SQL_BACKUP_IMPORTED_SUCCESS = "SQL backup imported successfully";
    public static final String MSG_ACCESS_DENIED_RESTORE = "Access denied for restore operation.";
    public static final String MSG_INVALID_SQL_BACKUP_FILE = "Invalid SQL backup file.";
    public static final String MSG_IMPORT_FAILED_PREFIX = "Import failed: ";
    public static final String MSG_DELETE_ALL_POST_ONLY = "Delete all must be submitted as a POST action.";
    public static final String MSG_DATA_DELETED_SUCCESS = "All questionBank data deleted successfully. Users, roles, and permissions were preserved.";
    public static final String MSG_ACCESS_DENIED_CLEANUP = "Access denied for cleanup operation.";
    public static final String MSG_DELETE_ALL_FAILED_PREFIX = "Delete all failed: ";
    public static final String MSG_ERROR_LOADING_PAGE_RETRY = "Error loading page. Please try again.";
    public static final String MSG_ERROR_PROCESSING_ACTION_RETRY = "Error processing action. Please try again.";
    public static final String MSG_RECOMPUTE_SAVE_HISTORY_SUCCESS = "Recompute result saved to history successfully.";
    public static final String MSG_RECOMPUTE_SAVE_HISTORY_FAILED = "Failed to save recompute result to history.";
    public static final String MSG_HISTORY_ENTRY_DELETED_SUCCESS = "History entry deleted successfully.";
    public static final String MSG_HISTORY_ENTRY_NOT_FOUND = "History entry not found.";
    public static final String MSG_HISTORY_ENTRY_DELETE_FAILED = "Failed to delete history entry.";
    public static final String MSG_FAILED_RECOMPUTE_DUPLICATES = "Failed to recompute duplicates.";
    public static final String MSG_FAILED_RETRIEVE_STATISTICS = "Failed to retrieve statistics.";
    public static final String MSG_ERROR_RETRIEVING_STATISTICS = "Error retrieving statistics. Please try again.";
    public static final String MSG_FAILED_CLEAR_DUPLICATES = "Failed to clear duplicates.";
    public static final String MSG_ERROR_CLEARING_DUPLICATES = "Error clearing duplicates. Please try again.";
    public static final String MSG_STATISTICS_RETRIEVED_FOR_PREFIX = "Statistics retrieved for: ";
    public static final String MSG_SUCCESS_CLEARED_PREFIX = "Successfully cleared ";
    public static final String MSG_DUPLICATE_LINKS_FOR_PREFIX = " duplicate links for: ";
    public static final String MSG_COURSE_NOT_FOUND_SHOWING_ALL_PREFIX = "Course '";
    public static final String MSG_COURSE_NOT_FOUND_SHOWING_ALL_SUFFIX = "' was not found. Showing all question banks.";
    public static final String MSG_ERROR_NOT_FOUND = "Error not found.";
    public static final String MSG_ERROR_RESOLVED_SUCCESS = "Error marked as resolved successfully.";
    public static final String MSG_ERROR_DELETED_SUCCESS = "Error deleted successfully.";
    public static final String MSG_ERROR_RESOLVE_FORBIDDEN = "You do not have permission to resolve errors.";
    public static final String MSG_ERROR_DELETE_FORBIDDEN = "You do not have permission to delete errors.";
    public static final String MSG_ERROR_RESOLVE_FAILED = "Failed to resolve error. Please try again.";
    public static final String MSG_ERROR_DELETE_FAILED = "Failed to delete error. Please try again.";
    public static final String MSG_LOGIN_REQUIRED_TO_VIEW_ERRORS = "Please log in to view errors.";
    public static final String MSG_ERROR_VIEW_FORBIDDEN = "You do not have permission to view errors.";
    public static final String MSG_ERROR_LOAD_FAILED = "Could not load errors. Please try again later.";
    public static final String MSG_QUESTION_BANK_CREATED_SUCCESS = "Question Bank created successfully";
    public static final String MSG_QUESTION_BANK_UPDATED_SUCCESS = "Question Bank updated successfully";
    public static final String MSG_QUESTION_BANK_DELETED_SUCCESS = "Question bank deleted successfully!";
    public static final String MSG_QUESTION_BANK_NOT_FOUND_DELETED = "QuestionBank not found. It may have been deleted.";
    public static final String MSG_QUESTION_BANK_DETAILS_UNAVAILABLE = "QuestionBank details are not available right now. Please refresh and try again.";
    public static final String MSG_QUESTION_BANK_EXPORT_VIEW_UNAVAILABLE = "QuestionBank export view is not available right now. Please refresh and try again.";
    public static final String MSG_QUESTION_BANK_CREATE_FAILED = "Could not create question bank. Please try again later.";
    public static final String MSG_QUESTION_BANK_LOAD_FAILED = "Could not load questionBank. Please try again later.";
    public static final String MSG_QUESTION_BANK_LOAD_FOR_EDIT_FAILED = "Could not load questionBank for editing. Please try again later.";
    public static final String MSG_QUESTION_BANK_UPDATE_FAILED = "Could not update question bank. Please try again later.";
    public static final String MSG_QUESTION_BANK_SAVE_FAILED = "Could not save question bank. Please try again later.";
    public static final String MSG_QUESTION_BANK_DELETE_FAILED = "Could not delete question bank. Please try again later.";
    public static final String MSG_QUESTION_BANK_NOT_FOUND = "QuestionBank not found.";
    public static final String MSG_COULD_NOT_LOAD_QUESTION_BANKS = "Could not load question banks. Please try again later.";
    public static final String MSG_COULD_NOT_LOAD_EXPORT_VIEW = "Could not load the export view. Please try again later.";
    public static final String MSG_COULD_NOT_LOAD_STATISTICS = "Could not load statistics. Please try again later.";
    public static final String MSG_ACCESS_DENIED_PLAIN = "Access denied.";
    public static final String MSG_UPLOAD_INVALID_STUDY_YEAR = "Please select a valid study year";
    public static final String MSG_UPLOAD_EXCEL_SUCCESS_PREFIX = "Excel file uploaded successfully. ";
    public static final String MSG_UPLOAD_EXCEL_FAILED_PREFIX = "Excel file upload failed: ";
    public static final String MSG_UPLOAD_ARCHIVE_REQUIRED = "Archive file is required";
    public static final String MSG_UPLOAD_COURSE_ID_REQUIRED = "Course ID is required";
    public static final String MSG_UPLOAD_QUESTION_BANK_REQUIRED = "QuestionBank name is required";
    public static final String MSG_UPLOAD_ARCHIVE_SUCCESS_PREFIX = "Archive uploaded successfully. ";
    public static final String MSG_UPLOAD_ARCHIVE_FAILED_PREFIX = "Archive upload failed: ";
    public static final String MSG_UPLOAD_ARCHIVE_IO_FAILED_PREFIX = "Archive file upload failed: ";
    public static final String MSG_UPLOAD_ARCHIVE_UNEXPECTED_FAILED_PREFIX = "Archive upload failed with unexpected error: ";
    public static final String MSG_UPLOAD_ARCHIVE_FOLDER_SELECT = "Please select a folder containing ZIP archives";
    public static final String MSG_UPLOAD_ARCHIVE_FOLDER_ONE_FILE = "Please select at least one archive file";
    public static final String MSG_UPLOAD_ARCHIVE_FOLDER_EMPTY_RESPONSE = "Folder upload finished with empty response";
    public static final String MSG_UPLOAD_ARCHIVE_FOLDER_FAILED_PREFIX = "Archive folder upload failed: ";
    public static final String MSG_UPLOAD_ARCHIVE_FOLDER_IO_FAILED_PREFIX = "Archive folder upload failed due to file read error: ";
    public static final String MSG_UPLOAD_ARCHIVE_FOLDER_UNEXPECTED_FAILED_PREFIX = "Folder upload failed with unexpected error: ";
    public static final String MSG_UPLOAD_XML_REQUIRED = "XML file is required";
    public static final String MSG_UPLOAD_XML_SUCCESS_PREFIX = "XML uploaded successfully. ";
    public static final String MSG_UPLOAD_XML_FAILED_PREFIX = "XML upload failed: ";
    public static final String MSG_UPLOAD_XML_IO_FAILED_PREFIX = "XML upload failed due to file read error: ";
    public static final String MSG_UPLOAD_XML_UNEXPECTED_FAILED_PREFIX = "XML upload failed with unexpected error: ";
    public static final String MSG_UPLOAD_FOLDER_PROCESSING_STARTED_PREFIX = "Folder processing started. Total archives: ";
    public static final String MSG_UPLOAD_FOLDER_READY_PREFIX = "Ready. Processed ";
    public static final String MSG_UPLOAD_FOLDER_READY_MIDDLE = " archive(s) from ";
    public static final String MSG_UPLOAD_FOLDER_READY_SKIPPED = " (Skipped: ";
    public static final String MSG_UPLOAD_FOLDER_READY_FAILED = ", Failed: ";
    public static final String MSG_UPLOAD_FOLDER_READY_SUFFIX = ").";
    // Question
    public static final String ATTR_QUESTIONS = "questions";
    public static final String ATTR_AUTHORS = "authors";
    public static final String ATTR_QUESTION_BANKS = "questionBanks";
    public static final String ATTR_QUESTION = "question";
    public static final String ATTR_SUCCESS_MESSAGE = "successMessage";
    public static final String ATTR_ERROR_MESSAGE = "errorMessage";
    public static final String ATTR_DUPLICATE_QUESTION_IDS = "duplicateQuestionIds";
    public static final String VIEW_QUESTION_LIST = "question-list";
    public static final String VIEW_QUESTION_VIEW = "question-view";
    public static final String VIEW_QUESTION_DUPLICATES = "question-duplicates";
    public static final String QUESTION_EDITOR_MULTICHOICE = "question-editor-mc";
    public static final String QUESTION_EDITOR_TRUEFALSE = "question-editor-tf";
    public static final String VIEW_REDIRECT_QUESTIONS = "redirect:/questions";
    public static final String API_QUESTIONS = "/questions";
    public static final String API_QUESTIONS_FILTER = "/questions/filter";
    public static final String API_QUESTION_BANKS = "/question-banks";
    public static final String API_QUESTION_BANKS_SLASH = "/question-banks/";
    public static final String API_QUESTION_BANKS_FILTER = "/question-banks/filter";
    public static final String API_QUESTION_BANKS_GET_BY_ID = "/question-banks/{questionBankId}";
    public static final String API_QUESTION_BANKS_GET_BY_ID_AND_AUTHOR_ID = "/author/{authorId}/question-banks/{questionBankId}";
    public static final String API_QUESTION_BANKS_DUPLICATES_REMOVE_BY_ID = "/{id:\\d+}/duplicates/remove";
    public static final String API_QUESTION_BANKS_DUPLICATES_REMOVE_ALL_BY_ID = "/{id:\\d+}/duplicates/remove-all";
    public static final String API_QUESTION_SAMPLE = "/sample";
    public static final String API_QUESTION_DUPLICATES = "/duplicates";
    public static final String API_QUESTION_DUPLICATES_REMOVE = "/duplicates/remove";
    public static final String API_QUESTION_DUPLICATES_REMOVE_ALL = "/duplicates/remove-all";
    public static final String API_QUESTION_EDIT = "/edit";
    public static final String API_QUESTION_CORRECTION = "/correction";
    public static final String API_QUESTION_CORRECTION_GRAMMAR = "/correction/grammar";
    public static final String API_QUESTION_CORRECTION_IMPROVE = "/correction/improve";
    public static final String API_QUESTION_CORRECTION_ALTERNATIVES = "/correction/alternatives";
    public static final String API_QUESTION_CORRECTION_EXPLANATION = "/correction/explanation";
    public static final String API_QUESTION_CORRECTION_SAVE = "/correction/save";
    public static final String API_AUTHORS = "/authors";
    public static final String API_AUTHORS_BY_NAME = "/authors/name/";
    public static final String API_AUTHORS_FILTER = "/authors/filter";
    public static final String API_AUTHORS_SEARCH = "/authors/search";
    public static final String API_AUTHORS_DETAILS_SUFFIX = "/details";
    public static final String API_AUTHORS_QUESTIONS_SUFFIX = "/questions";
    public static final String DEFAULT_AUTHOR = "Max Mustermann";
    public static final String DEFAULT_COURSE = "Unknown Course";
    public static final String DEFAULT_QUESTION_BANK = "Default Question Bank";
    public static final String DEFAULT_CORRECTION_LANGUAGE = "ro";
    public static final String REDIRECT_QUESTIONS_PREFIX = "redirect:/questions/";
    public static final String QUESTIONS_PATH_PREFIX = "/questions/";

    public static final String LOG_QUESTION_NOT_FOUND = "Question {} not found";
    public static final String LOG_CORRECTION_SERVICE_ERROR = "Correction service error for question {}: {}";
    public static final String MSG_QUESTION_NOT_FOUND = "Question not found";
    public static final String MSG_QUESTION_NOT_FOUND_WITH_ID_PREFIX = "Question not found with ID: ";
    public static final String MSG_ERROR_LOADING_QUESTION = "Error loading question";
    public static final String MSG_LOGIN_REQUIRED_TO_VIEW_QUESTIONS = "Please log in to view questions.";
    public static final String MSG_QUESTION_UPDATED_SUCCESS = "Question updated successfully";
    public static final String MSG_QUESTION_CREATED_SUCCESS = "Question created successfully";
    public static final String MSG_SESSION_EXPIRED_LOGIN_AGAIN = "Session expired. Please log in again.";
    public static final String MSG_SAVE_QUESTION_FAILED_PREFIX = "Failed to save question: ";
    public static final String MSG_QUESTION_DELETED_SUCCESS = "Question deleted successfully";
    public static final String MSG_UNABLE_LOAD_QUESTION_FOR_EDIT = "Unable to load question for edit.";
    public static final String MSG_UNABLE_LOAD_DUPLICATES = "Unable to load duplicate questions.";
    public static final String MSG_SELECT_AT_LEAST_ONE_DUPLICATE = "Select at least one duplicate question to remove.";
    public static final String MSG_DUPLICATES_REMOVED_SUCCESS = "Selected duplicate links removed successfully.";
    public static final String MSG_DUPLICATES_REMOVED_FAILED = "Failed to remove selected duplicate links.";
    public static final String MSG_ALL_DUPLICATES_REMOVED_SUCCESS = "All duplicate links removed successfully.";
    public static final String MSG_ALL_DUPLICATES_REMOVED_FAILED = "Failed to remove all duplicate links.";
    public static final String MSG_DUPLICATE_RESOLVED_SUCCESS = "Duplicate marked as resolved.";
    public static final String MSG_DUPLICATE_RESOLVED_FAILED = "Failed to mark duplicate as resolved.";
    public static final String MSG_UNEXPECTED_ERROR_RETRY_LATER = "Unexpected error. Please try again later.";
    // Author messages
    public static final String MSG_AUTHOR_NOT_FOUND = "Author not found with ID: ";
    public static final String MSG_AUTHOR_NOT_FOUND_PLAIN = "Author not found.";
    public static final String MSG_AUTHOR_DETAILS_NOT_FOUND = "Author details not found.";
    public static final String MSG_COULD_NOT_LOAD_AUTHOR_DETAILS = "Could not load author details. Please try again.";
    public static final String MSG_ERROR_LOADING_AUTHOR_PREFIX = "Error loading author: ";
    public static final String MSG_AUTHOR_CREATED_SUCCESS = "Author created successfully";
    public static final String MSG_AUTHOR_UPDATED_SUCCESS = "Author updated successfully";
    public static final String MSG_AUTHOR_DELETED_SUCCESS = "Author deleted successfully";
    public static final String MSG_AUTHOR_NAME_REQUIRED = "Author name is required.";
    public static final String MSG_AUTHOR_INITIALS_REQUIRED = "Author initials are required.";
    public static final String MSG_AUTHOR_CREATE_FAILED_PREFIX = "Failed to create author: ";
    public static final String MSG_AUTHOR_UPDATE_FAILED_PREFIX = "Failed to update author: ";
    public static final String MSG_NOT_AUTHENTICATED = "Not authenticated";
    public static final String MSG_AUTHOR_DELETED_AJAX = "Author deleted";

    // Question bank
    public static final String ATTR_SELECTED_QUESTION_BANK = "selectedQuestionBank";
    public static final String ATTR_QUESTION_BANK = "questionBank";
    public static final String ATTR_QUESTION_BANK_FILTER = "questionBankFilter";
    public static final String ATTR_ERROR_MSG = "errorMsg";
    public static final String VIEW_QUESTION_BANK_LIST = "question-bank-list";
    public static final String VIEW_QUESTION_BANK_DETAILS = "question-bank-details";
    public static final String VIEW_QUESTION_BANK_EXTENDED_DETAILS = "question-bank-extended-details";
    public static final String VIEW_QUESTION_BANK_STATISTICS = "question-bank-statistics";
    public static final String VIEW_DUPLICATE_RECOMPUTE = "duplicate-recompute";
    public static final String QUESTION_BANK_EDITOR = "question-bank-editor";
     public static final String VIEW_REDIRECT_QUESTION_BANK = "redirect:/question-banks";
     public static final String VIEW_REDIRECT_AUTH_LOGIN = "redirect:/auth/login";
    // Author
    public static final String ATTR_SELECTED_COURSE = "selectedCourse";
    public static final String ATTR_SELECTED_COURSE_ID = "selectedCourseId";
    public static final String ATTR_SELECTED_AUTHOR_ID = "selectedAuthorId";
    public static final String ATTR_SELECTED_AUTHOR = "selectedAuthor";
    public static final String VIEW_AUTHOR_LIST = "author-list";
    public static final String VIEW_AUTHOR_EDIT = "author-edit";
    public static final String VIEW_AUTHOR_DETAILS = "author-details";
    public static final String VIEW_REDIRECT_AUTHORS = "redirect:/authors";
    public static final String VIEW_SUCCESS = "success";

    public static final String ATTR_CURRENT_PAGE = "currentPage";
    public static final String ATTR_EDIT_MODE = "editMode";
    public static final String API_UPLOAD_EXCEL = "/upload/excel";
    public static final String API_UPLOAD_ARCHIVE = "/upload/archive";
    public static final String API_UPLOAD_ARCHIVE_FOLDER = "/upload/archive-folder";
    public static final String API_UPLOAD_XML = "/upload/xml";
    public static final String ATTR_STUDY_YEAR = "studyYear";
    public static final String ATTR_QUESTION_BANK_NAME = "questionBankName";

    public static final String ATTR_QUESTIONS_BY_QUESTION_BANK = "questionsByQuestionBank";
    public static final String ATTR_ERRORS_BY_QUESTION_BANK = "errorsByQuestionBank";

    // Additional question/pagination attributes
    public static final String ATTR_AUTHOR_ID = "authorId";
    public static final String ATTR_QUESTION_BANK_ID = "questionBankId";
    public static final String ATTR_SELECTED_TYPE = "selectedType";
    public static final String ATTR_SELECTED_QUESTION_BANK_ID = "selectedQuestionBankId";
    public static final String ATTR_AUTHOR_NAME = "authorName";

    // Question correction
    public static final String ATTR_CORRECTION_DTO = "correctionDto";
    public static final String VIEW_QUESTION_CORRECTION = "question-correction";
    public static final String RESPONSE_KEY_ALTERNATIVES = "alternatives";
    public static final String RESPONSE_KEY_EXPLANATION = "explanation";
    public static final String RESPONSE_KEY_STATUS = "status";
    public static final String RESPONSE_VALUE_SUCCESS = "success";

    // Home/Success page
    public static final String VIEW_HELP = "help";
    public static final String ATTR_MESSAGE_TYPE = "messageType";
    public static final String MESSAGE_TYPE_ERROR = "error";
    public static final String MESSAGE_TYPE_SUCCESS = "success";

    // PDF Check
    public static final String VIEW_CHECK_PDF = "check-pdf";
    public static final String RESPONSE_KEY_MESSAGE = "message";
    public static final String RESPONSE_KEY_ONLINE = "online";

     // Upload
     public static final String VIEW_UPLOAD_EXCEL = "upload-excel";
     public static final String VIEW_UPLOAD_ARCHIVE = "upload-archive";
     public static final String VIEW_UPLOAD_ARCHIVE_FOLDER = "upload-archive-folder";
     public static final String VIEW_UPLOAD_XML = "upload-xml";
     public static final String ATTR_TEMPLATES = "templates";
     public static final String ATTR_MESSAGE_BOX_LINES = "messageBoxLines";
     // Multipart field names
     public static final String FIELD_FILE = "file";
     public static final String FIELD_USERNAME = "username";
     public static final String FIELD_NAME = "name";
     public static final String FIELD_TEMPLATE = "template";
     public static final String FIELD_ARCHIVE = "archive";
     public static final String FIELD_ARCHIVES = "archives";
     public static final String FIELD_XML = "xml";

    public static final String UNKNOWN = "Unknown";

    // Errors
    public static final String VIEW_ERROR_LIST = "error-list";
    public static final String VIEW_REDIRECT_ERRORS = "redirect:/errors";
    public static final String API_ERRORS = "/errors";
    public static final String API_ERRORS_FILTER = "/errors/filter";
    public static final String API_DUPLICATES = "/duplicates";
    public static final String API_DUPLICATES_RESOLVE_BY_ID = "/{id}/resolve";
    public static final String ATTR_QUESTION_ERRORS = "questionErrors";
    public static final String ATTR_QUESTION_ERRORS_BY_AUTHOR = "questionErrorsByAuthor";
    public static final String ATTR_SELECTED_QUESTION_BANK_ID_ERRORS = "selectedQuestionBankIdErrors";
    public static final String ATTR_SELECTED_YEAR = "selectedYear";
    public static final String ATTR_YEARS = "years";
    public static final String ATTR_STUDY_YEARS = "studyYears";
    public static final String ATTR_AUTHOR_NAMES = "authorNames";
    public static final String ATTR_BACK_TO_ERRORS_URL = "backToErrorsUrl";
    public static final String ATTR_BACK_URL = "backUrl";
    public static final String ATTR_BACK_TO_AUTHORS_URL = "backToAuthorsUrl";
    public static final String ATTR_EDIT_AUTHOR_URL = "editAuthorUrl";
    public static final String ATTR_BACK_TO_QUESTION_BANK_URL = "backToQuestionBankUrl";
    public static final String ATTR_BACK_TO_QUESTIONS_URL = "backToQuestionsUrl";
    public static final String ATTR_QUESTION_EDIT_URL = "questionEditUrl";
    public static final String ATTR_QUESTION_DUPLICATES_URL = "questionDuplicatesUrl";
    public static final String ATTR_QUESTION_CORRECTION_URL = "questionCorrectionUrl";
    public static final String ATTR_QUESTION_VIEW_URL = "questionViewUrl";
    public static final String ATTR_JWT_TOKEN_PRESENT = "jwtTokenPresent";
    public static final String ATTR_QUESTION_BANK_EXTENDED = "questionBankExtended";
    public static final String ATTR_AUTHOR_SECTIONS = "authorSections";
    public static final String ATTR_STATISTICS = "statistics";
    public static final String ATTR_AVAILABLE_STRATEGIES = "availableStrategies";
    public static final String ATTR_SELECTED_STRATEGY = "selectedStrategy";
    public static final String ATTR_QUESTION_BANK_AUTHORS = "questionBankAuthors";
    public static final String ATTR_RECOMPUTE_HISTORY = "recomputeHistory";
    public static final String ATTR_RECOMPUTE_RESULT = "recomputeResult";
    public static final String ATTR_CLEAR_RESULT = "clearResult";
    public static final String ATTR_PENDING_STRATEGY = "pendingStrategy";
    public static final String ATTR_PENDING_COURSE_ID = "pendingCourseId";
    public static final String ATTR_PENDING_QUESTION_BANK_ID = "pendingQuestionBankId";
    public static final String ATTR_PENDING_AUTHOR_ID = "pendingAuthorId";
    public static final String ATTR_AUTHOR_STATS = "authorStats";
    public static final String ATTR_PERMISSIONS = "permissions";
    public static final String ATTR_ROLES = "roles";
    public static final String ATTR_ROLE = "role";
    public static final String ATTR_ERROR = "error";
    public static final String ATTR_DUPLICATES = "duplicates";
    public static final String ATTR_REGISTRATION_SUCCESS = "registrationSuccess";
    public static final String ATTR_REGISTRATION_MESSAGE = "registrationMessage";
    public static final String ERROR_STATUS_OPEN = "OPEN";
    public static final String ERROR_STATUS_RESOLVED = "RESOLVED";
    public static final String DUPLICATE_STATUS_OPEN = "OPEN";
    public static final String DUPLICATE_STATUS_RESOLVED = "RESOLVED";

    // Permission constants
    public static final String PERMISSION_EXPORT_XML = "EXPORT_XML";
    public static final String PERMISSION_CLEAN_DATABASE = "CLEAN_DATABASE";
    public static final String PERMISSION_BACKUP_DATABASE = "BACKUP_DATABASE";
    public static final String PERMISSION_RESTORE_DATABASE = "RESTORE_DATABASE";

    // Response keys and values
    public static final String KEY_ERROR = "error";
    public static final String KEY_TIMESTAMP = "timestamp";
    public static final String STATUS_KEY = "status";
    public static final String TIMESTAMP_KEY = "timestamp";
    public static final String ERROR_KEY = "error";
    public static final String SERVICE_KEY = "service";
    public static final String UP = "UP";
    public static final String DOWN = "DOWN";

    private ControllerSettings() {}

}

