package com.unitbv.myquiz.api.interfaces;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;

import java.util.Map;

/**
 * API interface for data cleanup operations.
 * This interface defines the contract for comprehensive data management endpoints.
 */
@Tag(name = "Data Management", description = "Data cleanup and management operations")
public interface DataCleanupApi {

    @Operation(summary = "Delete all questionBank data", description = "Deletes all questionBank-related data (questions, questionBanks, authors, courses) " + "while preserving user management data (users, roles, permissions)")
    @ApiResponses(value = {@ApiResponse(responseCode = "204", description = "All questionBank data deleted successfully"), @ApiResponse(responseCode = "500", description = "Internal server error")})
    @DeleteMapping("/deleteall")
    ResponseEntity<Void> deleteAllData();

    @Operation(summary = "Get database statistics", description = "Returns count of all entities in the database as key-value pairs. " + "Extended statistics (users, roles, permissions) are only included for users with canViewExtendedStatistics permission.")
    @ApiResponses(value = {@ApiResponse(responseCode = "200", description = "Statistics retrieved successfully"), @ApiResponse(responseCode = "500", description = "Internal server error")})
    @GetMapping("/statistics")
    ResponseEntity<Map<String, Long>> getStatistics();

    @Operation(summary = "Export SQL backup", description = "Exports all non-auth application data as a SQL script. " + "Auth/IAM data (users, roles, permissions) is excluded.")
    @ApiResponses(value = {@ApiResponse(responseCode = "200", description = "SQL backup generated successfully"), @ApiResponse(responseCode = "403", description = "Missing backup permission"), @ApiResponse(responseCode = "500", description = "Internal server error")})
    @GetMapping(value = "/export-sql", produces = MediaType.APPLICATION_OCTET_STREAM_VALUE)
    ResponseEntity<byte[]> exportSqlBackup();

    @Operation(summary = "Import SQL backup", description = "Imports a SQL backup file generated by export endpoint into non-auth tables only.")
    @ApiResponses(value = {@ApiResponse(responseCode = "200", description = "SQL backup imported successfully"), @ApiResponse(responseCode = "400", description = "Invalid SQL file"), @ApiResponse(responseCode = "403", description = "Missing restore permission"), @ApiResponse(responseCode = "500", description = "Internal server error")})
    @PostMapping(value = "/import-sql", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    ResponseEntity<String> importSqlBackup(@RequestParam("file") MultipartFile file);
}

