CREATE TABLE author (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name VARCHAR(255),
     initials VARCHAR(255)
);

CREATE TABLE course (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     course VARCHAR(255),
     description VARCHAR(255),
     university_year VARCHAR(255),
     semester VARCHAR(255),
     study_year VARCHAR(255)
);

CREATE TABLE quiz (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name VARCHAR(255),
     course VARCHAR(255),
     year BIGINT
);

CREATE TABLE quiz_author (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     author_id BIGINT,
     quiz_id BIGINT,
     source VARCHAR(255),
     template_type VARCHAR(255),
     CONSTRAINT fk_quiz_author_on_author FOREIGN KEY (author_id) REFERENCES author (id),
     CONSTRAINT fk_quiz_author_on_quiz FOREIGN KEY (quiz_id) REFERENCES quiz (id)
);

CREATE TABLE quiz_error (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     description VARCHAR(512),
     row_number INTEGER,
     quiz_author_id BIGINT,
     CONSTRAINT fk_quiz_error_on_quiz_author FOREIGN KEY (quiz_author_id) REFERENCES quiz_author (id)
);

CREATE TABLE question (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     crt_no INTEGER NOT NULL,
     chapter VARCHAR(255),
     title VARCHAR(255),
     text VARCHAR(1024),
     type VARCHAR(255),
     weight_response1 DOUBLE PRECISION,
     response1 VARCHAR(1024),
     weight_response2 DOUBLE PRECISION,
     response2 VARCHAR(1024),
     weight_response3 DOUBLE PRECISION,
     response3 VARCHAR(1024),
     weight_response4 DOUBLE PRECISION,
     response4 VARCHAR(1024),
     weight_true DOUBLE PRECISION,
     weight_false DOUBLE PRECISION,
     quiz_author_id BIGINT,
     CONSTRAINT fk_question_on_quiz_author FOREIGN KEY (quiz_author_id) REFERENCES quiz_author (id)
);

CREATE INDEX idx_question_quiz_author_id ON question (quiz_author_id);
CREATE INDEX idx_question_type ON question (type);

CREATE TABLE question_error (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     question_id BIGINT NOT NULL,
     quiz_error_id BIGINT NOT NULL,
     CONSTRAINT fk_question_error_on_question FOREIGN KEY (question_id) REFERENCES question (id),
     CONSTRAINT fk_question_error_on_quiz_error FOREIGN KEY (quiz_error_id) REFERENCES quiz_error (id)
);
