-- =====================================================
-- Fix: Update question_bank_study_year_check constraint
-- =====================================================
-- Problem: The check constraint was auto-generated by Hibernate
-- when StudyYear enum only had values up to Y2024_2025.
-- New enum values Y2025_2026 and Y2026_2027 were added to Java
-- but the DB constraint was never updated.
--
-- Run this script once against the live database to apply the fix.
-- =====================================================

-- Drop the outdated check constraint
ALTER TABLE question_bank DROP CONSTRAINT IF EXISTS question_bank_study_year_check;

-- Re-add constraint with all current StudyYear enum values
ALTER TABLE question_bank ADD CONSTRAINT question_bank_study_year_check
    CHECK (study_year IN (
        'Y2020_2021',
        'Y2021_2022',
        'Y2022_2023',
        'Y2024_2025',
        'Y2025_2026',
        'Y2026_2027'
    ));

-- Verify
DO $$
BEGIN
    RAISE NOTICE 'question_bank_study_year_check constraint updated successfully.';
    RAISE NOTICE 'Allowed values: Y2020_2021, Y2021_2022, Y2022_2023, Y2024_2025, Y2025_2026, Y2026_2027';
END $$;

